### ISSUE TITLE
line 48 q_pi_r_tilda in birl.py file

### ISSUE THREAD

**Issue by yichong96** [uidilr/bayesian_irl#1]
Hi ! thank you for posting the BIRL algorithm for everyone's learning. May i check if this line of code is correct ? because the model being used to compute q_pi_r_tilda is the env model which contains the reward, R (step 1) rather than the reward of r_tilda as described in the BIRL algorithm ?

**Comment by uidilr** [comment]
Hi Yi,

We update the environment in the following lines so that it is not
necessarily a reward vector from step1.
https://github.com/uidilr/bayesian_irl/blob/1c03e6b0aeb92379f189c4426d6635418504d5ad/src/birl.py#L46
https://github.com/uidilr/bayesian_irl/blob/1c03e6b0aeb92379f189c4426d6635418504d5ad/src/birl.py#L49

Hope it helps!

**Comment by yichong96** [comment]
All right thank you !
